// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://plzfhrjninkxvwsnyrce.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBsemZocmpuaW5reHZ3c255cmNlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU5NzA2MjcsImV4cCI6MjA3MTU0NjYyN30.FImUDAkdyZ0R-qwhgjTxzkVXU47PWW48vrISfmDcg1w";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});